import React, { useState, useEffect, useRef } from 'react';
import { useLocation, Link } from 'react-router-dom';
import { useFileContext } from '../../context/FileContext';
import {
  ShieldCheck, AlertTriangle, Terminal, Key, Hash, FileCode,
  MapPin, Camera, Search, Copy, Check, Download, BookOpen,
  Eye, RefreshCw, UploadCloud, Layers, ExternalLink, Cpu, Info, Bug
} from 'lucide-react';
import {
  computeFileHashes,
  computeShannonEntropy,
  identifyMagicBytes,
  extractExifMetadata,
  extractPdfForensics,
  extractPrintableStrings,
  formatHexDump
} from '../../utils/forensicsUtils';

export default function CyberForensicsInvestigator() {
  const location = useLocation();
  const { sharedFile, clearFile } = useFileContext();

  const [file, setFile] = useState(null);
  const [isAnalyzing, setIsAnalyzing] = useState(false);
  const [activeTab, setActiveTab] = useState('overview'); // 'overview' | 'tampering' | 'metadata' | 'strings' | 'hex' | 'guide'

  // Forensic Data
  const [hashes, setHashes] = useState(null);
  const [magicData, setMagicData] = useState(null);
  const [entropy, setEntropy] = useState(null);
  const [exifData, setExifData] = useState(null);
  const [pdfData, setPdfData] = useState(null);
  const [stringsData, setStringsData] = useState([]);
  const [hexRows, setHexRows] = useState([]);
  const [hexViewMode, setHexViewMode] = useState('header'); // 'header' | 'trailer'

  // Filtering & Copying
  const [stringCategoryFilter, setStringCategoryFilter] = useState('ALL');
  const [stringSearch, setStringSearch] = useState('');
  const [copiedKey, setCopiedKey] = useState(null);
  const fileInputRef = useRef(null);

  // Auto-load file from FileContext or navigation state
  useEffect(() => {
    const incomingFile = location.state?.autoLoadedFile || sharedFile;
    if (incomingFile) {
      handleFileAnalysis(incomingFile);
      if (clearFile) clearFile();
    }
  }, [location.state, sharedFile]);

  const copyToClipboard = (text, key) => {
    navigator.clipboard.writeText(text);
    setCopiedKey(key);
    setTimeout(() => setCopiedKey(null), 1800);
  };

  const handleFileAnalysis = async (selectedFile) => {
    if (!selectedFile) return;
    setFile(selectedFile);
    setIsAnalyzing(true);

    // For very large files (>200MB), skip string extraction to avoid UI freeze
    const LARGE_FILE_THRESHOLD = 200 * 1024 * 1024; // 200MB
    const isLargeFile = selectedFile.size > LARGE_FILE_THRESHOLD;

    try {
      const arrayBuffer = await selectedFile.arrayBuffer();
      const uint8Array = new Uint8Array(arrayBuffer);

      // Run all analyses concurrently — 2x faster than sequential awaits
      const [computedHashes, magic, computedEntropy, exif, pdf, carvedStrings] = await Promise.all([
        // 1. Hashes (SHA-1/256/512 via Web Crypto in parallel + non-blocking MD5)
        computeFileHashes(arrayBuffer),
        // 2. Magic Bytes & Masquerade detection (synchronous, fast)
        Promise.resolve(identifyMagicBytes(uint8Array, selectedFile.name)),
        // 3. Shannon Entropy (synchronous, fast O(n) loop)
        Promise.resolve(computeShannonEntropy(uint8Array)),
        // 4. Image EXIF & GPS
        Promise.resolve(extractExifMetadata(arrayBuffer)),
        // 5. PDF Forensics
        Promise.resolve(extractPdfForensics(arrayBuffer)),
        // 6. Strings Extraction — skipped for large files to prevent UI freeze
        isLargeFile
          ? Promise.resolve([{ value: `⚡ File is ${(selectedFile.size / 1024 / 1024).toFixed(0)}MB — string extraction is deferred for large files. Click "Load Strings" below to run it.`, category: 'INFO', offset: 0 }])
          : Promise.resolve(extractPrintableStrings(uint8Array, 4, 300)),
      ]);

      setHashes(computedHashes);
      setMagicData(magic);
      setEntropy(computedEntropy);
      setExifData(exif);
      setPdfData(pdf);
      setStringsData(carvedStrings);

      // 7. Hex Dump (Header default)
      updateHexView(uint8Array, 'header');
    } catch (err) {
      console.error('Forensics analysis failed:', err);
    } finally {
      setIsAnalyzing(false);
    }
  };

  const updateHexView = async (uint8ArrayOrFile, mode) => {
    setHexViewMode(mode);
    let bytes = uint8ArrayOrFile;
    if (!(bytes instanceof Uint8Array)) {
      if (!file) return;
      const buf = await file.arrayBuffer();
      bytes = new Uint8Array(buf);
    }

    if (mode === 'header') {
      setHexRows(formatHexDump(bytes, 384, 0));
    } else {
      const start = Math.max(0, bytes.length - 384);
      setHexRows(formatHexDump(bytes, 384, start));
    }
  };

  // Export Complete Forensic Case Report
  const exportForensicReport = () => {
    if (!file || !hashes) return;

    const report = {
      caseTitle: 'Digital Forensics Triage & Metadata Report',
      timestamp: new Date().toISOString(),
      examinerNotes: 'Generated by FileVerse Cyber Forensics Investigator (100% in-browser RAM execution)',
      fileInformation: {
        fileName: file.name,
        fileSizeBytes: file.size,
        declaredMimeType: file.type || 'application/octet-stream',
        lastModified: new Date(file.lastModified).toISOString(),
      },
      chainOfCustodyHashes: hashes,
      binarySignatureAnalysis: {
        hexHeader: magicData?.hexSignature,
        identifiedFormat: magicData?.detectedMatch?.name,
        typicalExtensions: magicData?.detectedMatch?.ext,
        isExtensionSpoofed: magicData?.isSpoofed,
        spoofWarning: magicData?.spoofWarning,
      },
      entropyAnalysis: {
        shannonEntropyBitsPerByte: entropy,
        interpretation:
          entropy > 7.2
            ? 'High Entropy (Likely Packed, Encrypted, or Heavily Compressed)'
            : entropy > 4.5
            ? 'Normal Structured Binary / Code'
            : 'Low Entropy (Plain Text or Sparse Data)',
      },
      geolocationAndExif: exifData?.gps
        ? {
            latitude: exifData.gps.latitude,
            longitude: exifData.gps.longitude,
            altitude: exifData.gps.altitude,
            cameraMake: exifData.cameraMake,
            cameraModel: exifData.cameraModel,
            software: exifData.software,
          }
        : 'No GPS Telemetry Found',
      pdfForensics: pdfData?.isPdf
        ? {
            version: pdfData.version,
            suspiciousStreams: pdfData.suspiciousStreams,
            metadata: pdfData.metadata,
          }
        : 'Not a PDF Document',
      stringsExtractedSummary: {
        totalSampled: stringsData.length,
        networkEndpoints: stringsData.filter((s) => s.category === 'URL' || s.category === 'IP').map((s) => s.text),
        suspiciousKeywordsFound: stringsData.filter((s) => s.category === 'SUSPICIOUS').map((s) => s.text),
      },
    };

    const blob = new Blob([JSON.stringify(report, null, 2)], { type: 'application/json' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `Forensic_Report_${file.name.replace(/\.[^/.]+$/, '')}_${Date.now()}.json`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const filteredStrings = stringsData.filter((item) => {
    const matchesCategory = stringCategoryFilter === 'ALL' || item.category === stringCategoryFilter;
    const matchesSearch = !stringSearch || item.text.toLowerCase().includes(stringSearch.toLowerCase());
    return matchesCategory && matchesSearch;
  });

  return (
    <div style={{ maxWidth: '1160px', margin: '0 auto', padding: '1.5rem 1rem 4rem 1rem', fontFamily: 'system-ui, -apple-system, sans-serif' }}>
      {/* Header Banner */}
      <div style={{
        background: '#090d16',
        borderRadius: '16px',
        padding: '2rem',
        color: '#ffffff',
        marginBottom: '1.75rem',
        position: 'relative',
        overflow: 'hidden',
        boxShadow: '0 10px 30px rgba(0,0,0,0.25)',
        border: '1px solid #1e293b'
      }}>
        <div style={{ position: 'relative', zIndex: 1 }}>
          <div style={{ display: 'inline-flex', alignItems: 'center', gap: '6px', background: '#1e293b', padding: '0.25rem 0.75rem', borderRadius: '9999px', fontSize: '0.75rem', fontWeight: 700, color: '#38bdf8', marginBottom: '0.75rem', letterSpacing: '0.5px' }}>
            <Terminal size={13} />
            <span>CYBERSECURITY & FORENSICS LAB</span>
          </div>
          <h1 style={{ fontSize: '2rem', fontWeight: 900, letterSpacing: '-0.5px', margin: '0 0 0.5rem 0' }}>
            Cyber Forensic Data Investigator
          </h1>
          <p style={{ color: '#94a3b8', fontSize: '0.95rem', maxWidth: '680px', margin: 0, lineHeight: 1.5 }}>
            Inspect hidden digital metadata, detect extension spoofing & anti-forensics, compute cryptographic chain-of-custody hashes, analyze Shannon entropy, carve strings, and study forensic triage concepts in real time.
          </p>

          <div style={{ display: 'flex', alignItems: 'center', gap: '1rem', marginTop: '1.25rem', flexWrap: 'wrap' }}>
            <div style={{ display: 'inline-flex', alignItems: 'center', gap: '6px', fontSize: '0.78rem', color: '#10b981', background: 'rgba(16, 185, 129, 0.12)', padding: '0.35rem 0.75rem', borderRadius: '6px', border: '1px solid rgba(16, 185, 129, 0.25)' }}>
              <ShieldCheck size={14} />
              <span>100% In-Browser Execution • Zero Server Network Egress</span>
            </div>
            <div style={{ display: 'inline-flex', alignItems: 'center', gap: '6px', fontSize: '0.78rem', color: '#94a3b8' }}>
              <BookOpen size={14} />
              <span>Built for Cybersecurity Students & Analysts</span>
            </div>
          </div>
        </div>
      </div>

      {/* File Ingestion Dropzone */}
      <div
        onClick={() => fileInputRef.current?.click()}
        style={{
          border: '2px dashed #cbd5e1',
          background: file ? '#f8fafc' : '#ffffff',
          borderRadius: '14px',
          padding: file ? '1.25rem 1.75rem' : '2.5rem 1.5rem',
          textAlign: 'center',
          cursor: 'pointer',
          marginBottom: '1.75rem',
          transition: 'all 0.2s ease',
          display: 'flex',
          flexDirection: file ? 'row' : 'column',
          alignItems: 'center',
          justifyContent: file ? 'space-between' : 'center',
          gap: '1rem'
        }}
        onMouseEnter={(e) => { e.currentTarget.style.borderColor = '#0f172a'; }}
        onMouseLeave={(e) => { e.currentTarget.style.borderColor = '#cbd5e1'; }}
      >
        <input
          ref={fileInputRef}
          type="file"
          style={{ display: 'none' }}
          onClick={(e) => { e.target.value = ''; }}
          onChange={(e) => {
            if (e.target.files?.[0]) handleFileAnalysis(e.target.files[0]);
          }}
        />

        {!file ? (
          <>
            <div style={{ width: '52px', height: '52px', borderRadius: '50%', background: '#f1f5f9', display: 'flex', alignItems: 'center', justifyContent: 'center', color: '#0f172a', marginBottom: '0.75rem' }}>
              <UploadCloud size={26} />
            </div>
            <h3 style={{ margin: '0 0 0.35rem 0', fontSize: '1.25rem', fontWeight: 800, color: '#0f172a' }}>
              Drop any file to begin forensic triage
            </h3>
            <p style={{ margin: 0, fontSize: '0.85rem', color: '#64748b' }}>
              Supports Images (EXIF/GPS), PDFs, Binaries (MZ/ELF), Office documents, Archives, and Scripts.
            </p>
          </>
        ) : (
          <>
            <div style={{ display: 'flex', alignItems: 'center', gap: '1rem', textAlign: 'left' }}>
              <div style={{ width: '44px', height: '44px', borderRadius: '10px', background: '#0f172a', color: '#ffffff', display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
                <Terminal size={22} />
              </div>
              <div>
                <div style={{ display: 'flex', alignItems: 'center', gap: '0.5rem' }}>
                  <span style={{ fontSize: '1.05rem', fontWeight: 800, color: '#0f172a' }}>{file.name}</span>
                  <span style={{ fontSize: '0.72rem', fontWeight: 700, background: '#e2e8f0', color: '#334155', padding: '0.15rem 0.5rem', borderRadius: '4px' }}>
                    {(file.size / 1024).toFixed(1)} KB
                  </span>
                </div>
                <div style={{ fontSize: '0.78rem', color: '#64748b', marginTop: '0.2rem' }}>
                  Identified: <strong>{magicData?.detectedMatch?.name || 'Inspecting...'}</strong>
                </div>
              </div>
            </div>

            <div style={{ display: 'flex', gap: '0.5rem' }}>
              <button
                type="button"
                onClick={(e) => {
                  e.stopPropagation();
                  fileInputRef.current?.click();
                }}
                style={{
                  background: '#ffffff',
                  border: '1px solid #cbd5e1',
                  color: '#0f172a',
                  padding: '0.45rem 0.85rem',
                  borderRadius: '6px',
                  fontSize: '0.8rem',
                  fontWeight: 600,
                  cursor: 'pointer',
                  display: 'flex',
                  alignItems: 'center',
                  gap: '4px'
                }}
              >
                <RefreshCw size={13} /> Change File
              </button>
              <button
                type="button"
                onClick={(e) => {
                  e.stopPropagation();
                  exportForensicReport();
                }}
                style={{
                  background: '#0f172a',
                  border: 'none',
                  color: '#ffffff',
                  padding: '0.45rem 1rem',
                  borderRadius: '6px',
                  fontSize: '0.8rem',
                  fontWeight: 700,
                  cursor: 'pointer',
                  display: 'flex',
                  alignItems: 'center',
                  gap: '5px'
                }}
              >
                <Download size={13} /> Export Report
              </button>
            </div>
          </>
        )}
      </div>

      {file && (
        <>
          {/* Extension Spoofing Warning Banner */}
          {magicData?.isSpoofed && (
            <div style={{
              background: '#fef2f2',
              border: '1px solid #fecaca',
              borderRadius: '12px',
              padding: '1rem 1.25rem',
              marginBottom: '1.5rem',
              display: 'flex',
              alignItems: 'flex-start',
              gap: '0.75rem',
              color: '#991b1b'
            }}>
              <AlertTriangle size={22} style={{ flexShrink: 0, marginTop: '2px' }} />
              <div>
                <h4 style={{ margin: '0 0 0.25rem 0', fontSize: '0.95rem', fontWeight: 800 }}>
                  ANTI-FORENSICS ALERT: Extension Masquerade Detected!
                </h4>
                <p style={{ margin: 0, fontSize: '0.85rem', lineHeight: 1.45 }}>
                  {magicData.spoofWarning}
                </p>
                <div style={{ marginTop: '0.5rem', fontSize: '0.78rem', color: '#b91c1c', background: '#fee2e2', padding: '0.4rem 0.75rem', borderRadius: '6px', display: 'inline-block' }}>
                  💡 <strong>Student Tip:</strong> Attackers disguise executable payloads as innocent PDFs or JPGs so users double-click them. Forensic tools inspect the first magic bytes rather than trusting the file name.
                </div>
              </div>
            </div>
          )}

          {/* Forensic Dashboard Key Metrics Bar */}
          <div style={{
            display: 'grid',
            gridTemplateColumns: 'repeat(auto-fit, minmax(240px, 1fr))',
            gap: '1rem',
            marginBottom: '1.5rem'
          }}>
            {/* Metric 1: Magic Bytes */}
            <div style={{ background: '#ffffff', border: '1px solid #e2e8f0', borderRadius: '12px', padding: '1rem 1.25rem', boxShadow: '0 2px 6px rgba(0,0,0,0.02)' }}>
              <div style={{ fontSize: '0.72rem', fontWeight: 700, color: '#64748b', textTransform: 'uppercase', letterSpacing: '0.5px', marginBottom: '0.35rem' }}>
                Header Signature (Magic Bytes)
              </div>
              <div style={{ fontFamily: 'monospace', fontSize: '0.9rem', fontWeight: 800, color: '#0f172a' }}>
                {magicData?.hexSignature ? magicData.hexSignature.slice(0, 23) : 'Calculating...'}
              </div>
              <div style={{ fontSize: '0.75rem', color: '#64748b', marginTop: '0.25rem' }}>
                ASCII: <code style={{ background: '#f1f5f9', padding: '1px 4px', borderRadius: '3px' }}>{magicData?.asciiSignature?.slice(0, 8) || '·'}</code>
              </div>
            </div>

            {/* Metric 2: Shannon Entropy */}
            <div style={{ background: '#ffffff', border: '1px solid #e2e8f0', borderRadius: '12px', padding: '1rem 1.25rem', boxShadow: '0 2px 6px rgba(0,0,0,0.02)' }}>
              <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '0.35rem' }}>
                <span style={{ fontSize: '0.72rem', fontWeight: 700, color: '#64748b', textTransform: 'uppercase', letterSpacing: '0.5px' }}>
                  Shannon Entropy
                </span>
                <span style={{ fontSize: '0.75rem', fontWeight: 800, color: entropy > 7.2 ? '#dc2626' : entropy > 4.5 ? '#2563eb' : '#16a34a' }}>
                  {entropy !== null ? `${entropy} / 8.0` : '...'}
                </span>
              </div>
              {/* Entropy Bar */}
              <div style={{ width: '100%', height: '8px', background: '#f1f5f9', borderRadius: '4px', overflow: 'hidden', margin: '0.4rem 0' }}>
                <div style={{
                  width: `${((entropy || 0) / 8.0) * 100}%`,
                  height: '100%',
                  background: entropy > 7.2 ? '#dc2626' : entropy > 4.5 ? '#2563eb' : '#16a34a',
                  transition: 'width 0.4s ease'
                }} />
              </div>
              <div style={{ fontSize: '0.75rem', color: '#64748b' }}>
                {entropy > 7.2
                  ? 'High (Likely packed, encrypted, or compressed)'
                  : entropy > 4.5
                  ? 'Normal (Structured code/document)'
                  : 'Low (Sparse or plain text)'}
              </div>
            </div>

            {/* Metric 3: Primary Hash (SHA-256) */}
            <div style={{ background: '#ffffff', border: '1px solid #e2e8f0', borderRadius: '12px', padding: '1rem 1.25rem', boxShadow: '0 2px 6px rgba(0,0,0,0.02)' }}>
              <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '0.35rem' }}>
                <span style={{ fontSize: '0.72rem', fontWeight: 700, color: '#64748b', textTransform: 'uppercase', letterSpacing: '0.5px' }}>
                  SHA-256 Hash
                </span>
                <button
                  onClick={() => copyToClipboard(hashes?.sha256, 'sha256-card')}
                  style={{ background: 'transparent', border: 'none', cursor: 'pointer', padding: 0, color: '#64748b' }}
                >
                  {copiedKey === 'sha256-card' ? <Check size={14} color="#16a34a" /> : <Copy size={14} />}
                </button>
              </div>
              <div style={{ fontFamily: 'monospace', fontSize: '0.78rem', fontWeight: 700, color: '#0f172a', overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' }}>
                {hashes?.sha256 || 'Computing...'}
              </div>
              <div style={{ fontSize: '0.75rem', color: '#16a34a', marginTop: '0.25rem' }}>
                ✓ Cryptographic Chain of Custody Ready
              </div>
            </div>
          </div>

          {/* Investigation Tabs Navigation */}
          <div style={{
            display: 'flex',
            gap: '0.5rem',
            borderBottom: '1px solid #e2e8f0',
            marginBottom: '1.5rem',
            overflowX: 'auto',
            paddingBottom: '0.25rem'
          }}>
            {[
              { id: 'overview', label: 'Overview & Hashes', icon: Hash },
              { id: 'tampering', label: 'Anti-Forensics & Threats', icon: ShieldCheck },
              { id: 'metadata', label: 'EXIF & Geolocation', icon: MapPin },
              { id: 'strings', label: 'Strings Hunter', icon: Search },
              { id: 'hex', label: 'Hex Inspector', icon: Terminal },
              { id: 'guide', label: 'Student Field Guide', icon: BookOpen },
            ].map(({ id, label, icon: TabIcon }) => (
              <button
                key={id}
                onClick={() => setActiveTab(id)}
                style={{
                  background: activeTab === id ? '#0f172a' : 'transparent',
                  color: activeTab === id ? '#ffffff' : '#64748b',
                  border: 'none',
                  padding: '0.6rem 1.15rem',
                  borderRadius: '8px',
                  fontWeight: 700,
                  fontSize: '0.85rem',
                  cursor: 'pointer',
                  display: 'flex',
                  alignItems: 'center',
                  gap: '6px',
                  whiteSpace: 'nowrap',
                  transition: 'all 0.15s ease'
                }}
              >
                <TabIcon size={15} />
                <span>{label}</span>
              </button>
            ))}
          </div>

          {/* TAB 1: OVERVIEW & CHAIN OF CUSTODY HASHES */}
          {activeTab === 'overview' && (
            <div style={{ background: '#ffffff', border: '1px solid #e2e8f0', borderRadius: '14px', padding: '1.5rem', boxShadow: '0 4px 16px -2px rgba(0,0,0,0.03)' }}>
              <h3 style={{ fontSize: '1.15rem', fontWeight: 800, color: '#0f172a', marginBottom: '0.5rem' }}>
                Chain of Custody Cryptographic Hashes
              </h3>
              <p style={{ fontSize: '0.85rem', color: '#64748b', marginBottom: '1.25rem' }}>
                In digital forensics, files must be cryptographically hashed immediately upon acquisition. If even 1 single bit changes, the hash alters completely (Avalanche effect).
              </p>

              <div style={{ display: 'flex', flexDirection: 'column', gap: '0.85rem', marginBottom: '1.5rem' }}>
                {[
                  { name: 'SHA-256', val: hashes?.sha256, standard: 'Forensic Standard (Collision Resistant)', badge: '#16a34a' },
                  { name: 'SHA-512', val: hashes?.sha512, standard: 'High-Security 512-bit digest', badge: '#2563eb' },
                  { name: 'SHA-1', val: hashes?.sha1, standard: 'Legacy (Collision prone, reference only)', badge: '#d97706' },
                  { name: 'MD5', val: hashes?.md5, standard: 'Legacy (Fast checksum, not secure)', badge: '#dc2626' },
                ].map(({ name, val, standard, badge }) => (
                  <div key={name} style={{ background: '#f8fafc', border: '1px solid #e2e8f0', borderRadius: '8px', padding: '0.85rem 1rem' }}>
                    <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '0.25rem' }}>
                      <div style={{ display: 'flex', alignItems: 'center', gap: '0.5rem' }}>
                        <span style={{ fontSize: '0.82rem', fontWeight: 800, color: '#0f172a' }}>{name}</span>
                        <span style={{ fontSize: '0.7rem', fontWeight: 600, color: badge, background: '#ffffff', padding: '1px 6px', borderRadius: '4px', border: '1px solid #e2e8f0' }}>
                          {standard}
                        </span>
                      </div>
                      <button
                        onClick={() => copyToClipboard(val, name)}
                        style={{ background: '#ffffff', border: '1px solid #cbd5e1', borderRadius: '4px', padding: '0.25rem 0.6rem', fontSize: '0.75rem', fontWeight: 600, color: '#0f172a', cursor: 'pointer', display: 'flex', alignItems: 'center', gap: '4px' }}
                      >
                        {copiedKey === name ? <Check size={13} color="#16a34a" /> : <Copy size={13} />}
                        <span>{copiedKey === name ? 'Copied' : 'Copy'}</span>
                      </button>
                    </div>
                    <div style={{ fontFamily: 'monospace', fontSize: '0.82rem', color: '#334155', wordBreak: 'break-all' }}>
                      {val || 'Calculating...'}
                    </div>
                  </div>
                ))}
              </div>

              {/* File Technical Spec Table */}
              <h4 style={{ fontSize: '0.95rem', fontWeight: 800, color: '#0f172a', marginBottom: '0.75rem' }}>
                Acquisition Telemetry
              </h4>
              <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(220px, 1fr))', gap: '0.75rem' }}>
                <div style={{ background: '#f8fafc', padding: '0.75rem', borderRadius: '6px', border: '1px solid #e2e8f0' }}>
                  <div style={{ fontSize: '0.72rem', color: '#64748b' }}>Exact File Size</div>
                  <div style={{ fontSize: '0.85rem', fontWeight: 700, color: '#0f172a' }}>{file.size.toLocaleString()} bytes</div>
                </div>
                <div style={{ background: '#f8fafc', padding: '0.75rem', borderRadius: '6px', border: '1px solid #e2e8f0' }}>
                  <div style={{ fontSize: '0.72rem', color: '#64748b' }}>Declared MIME Type</div>
                  <div style={{ fontSize: '0.85rem', fontWeight: 700, color: '#0f172a' }}>{file.type || 'None (Binary stream)'}</div>
                </div>
                <div style={{ background: '#f8fafc', padding: '0.75rem', borderRadius: '6px', border: '1px solid #e2e8f0' }}>
                  <div style={{ fontSize: '0.72rem', color: '#64748b' }}>Last Modified Timestamp</div>
                  <div style={{ fontSize: '0.85rem', fontWeight: 700, color: '#0f172a' }}>{new Date(file.lastModified).toUTCString()}</div>
                </div>
              </div>
            </div>
          )}

          {/* TAB 2: ANTI-FORENSICS & THREATS */}
          {activeTab === 'tampering' && (
            <div style={{ background: '#ffffff', border: '1px solid #e2e8f0', borderRadius: '14px', padding: '1.5rem', boxShadow: '0 4px 16px -2px rgba(0,0,0,0.03)' }}>
              <h3 style={{ fontSize: '1.15rem', fontWeight: 800, color: '#0f172a', marginBottom: '0.5rem' }}>
                Anti-Forensics & Tampering Diagnostics
              </h3>
              <p style={{ fontSize: '0.85rem', color: '#64748b', marginBottom: '1.5rem' }}>
                Malware authors and adversaries use anti-forensics to conceal payloads, confuse detection systems, and exploit reader applications.
              </p>

              {/* Shannon Entropy In-Depth Box */}
              <div style={{ background: '#f8fafc', border: '1px solid #e2e8f0', borderRadius: '10px', padding: '1.25rem', marginBottom: '1.25rem' }}>
                <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '0.5rem' }}>
                  <h4 style={{ margin: 0, fontSize: '0.95rem', fontWeight: 800, color: '#0f172a', display: 'flex', alignItems: 'center', gap: '6px' }}>
                    <Cpu size={16} /> Shannon Entropy Analysis ({entropy} bits/byte)
                  </h4>
                  <span style={{ fontSize: '0.75rem', fontWeight: 700, padding: '0.2rem 0.6rem', borderRadius: '9999px', background: entropy > 7.2 ? '#fee2e2' : '#f1f5f9', color: entropy > 7.2 ? '#991b1b' : '#334155' }}>
                    {entropy > 7.2 ? 'HIGH ENTROPY' : entropy > 4.5 ? 'MODERATE' : 'LOW ENTROPY'}
                  </span>
                </div>
                <p style={{ fontSize: '0.82rem', color: '#475569', lineHeight: 1.45, margin: '0 0 0.75rem 0' }}>
                  Shannon entropy measures the randomness or unpredictability of data in a file. High entropy ($&gt; 7.2$) indicates encryption, compressed data, or <strong>packed malware / encrypted shellcode</strong>.
                </p>
                <div style={{ background: '#ffffff', border: '1px solid #e2e8f0', borderRadius: '6px', padding: '0.65rem 0.85rem', fontSize: '0.78rem', color: '#334155' }}>
                  💡 <strong>Student Context:</strong> If a document file or non-compressed file (e.g. <code>.txt</code> or <code>.vbs</code>) shows entropy above 7.0, investigate for embedded Base64, obfuscated payload, or XOR-encrypted droppers.
                </div>
              </div>

              {/* PDF Suspicious Streams (if PDF) */}
              {pdfData?.isPdf && (
                <div style={{ background: '#f8fafc', border: '1px solid #e2e8f0', borderRadius: '10px', padding: '1.25rem', marginBottom: '1.25rem' }}>
                  <h4 style={{ margin: '0 0 0.5rem 0', fontSize: '0.95rem', fontWeight: 800, color: '#0f172a', display: 'flex', alignItems: 'center', gap: '6px' }}>
                    <Bug size={16} /> Weaponized PDF Exploit Stream Scanner
                  </h4>
                  <p style={{ fontSize: '0.82rem', color: '#475569', margin: '0 0 0.75rem 0' }}>
                    PDF documents support interactive actions. Attackers inject <code>/JavaScript</code> or <code>/Launch</code> directives to trigger arbitrary command execution.
                  </p>

                  {pdfData.suspiciousStreams.length === 0 ? (
                    <div style={{ color: '#16a34a', fontSize: '0.82rem', fontWeight: 700, display: 'flex', alignItems: 'center', gap: '6px' }}>
                      <Check size={16} /> No weaponized or suspicious PDF action streams detected.
                    </div>
                  ) : (
                    <div style={{ display: 'flex', flexDirection: 'column', gap: '0.5rem' }}>
                      {pdfData.suspiciousStreams.map((item, idx) => (
                        <div key={idx} style={{ background: '#fee2e2', border: '1px solid #fca5a5', padding: '0.5rem 0.75rem', borderRadius: '6px', display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
                          <span style={{ fontFamily: 'monospace', fontWeight: 800, color: '#991b1b', fontSize: '0.85rem' }}>{item.token} ({item.count} occurrences)</span>
                          <span style={{ fontSize: '0.75rem', color: '#7f1d1d', fontWeight: 600 }}>{item.desc}</span>
                        </div>
                      ))}
                    </div>
                  )}
                </div>
              )}
            </div>
          )}

          {/* TAB 3: METADATA & GEOLOCATION */}
          {activeTab === 'metadata' && (
            <div style={{ background: '#ffffff', border: '1px solid #e2e8f0', borderRadius: '14px', padding: '1.5rem', boxShadow: '0 4px 16px -2px rgba(0,0,0,0.03)' }}>
              <h3 style={{ fontSize: '1.15rem', fontWeight: 800, color: '#0f172a', marginBottom: '0.5rem' }}>
                Digital Metadata & Geolocation (OSINT)
              </h3>
              <p style={{ fontSize: '0.85rem', color: '#64748b', marginBottom: '1.5rem' }}>
                Files inadvertently leak hardware models, software versions, editing traces, and exact geographic coordinates where photos were captured.
              </p>

              {/* GPS Geolocation Box */}
              {exifData?.gps ? (
                <div style={{ background: '#f0fdf4', border: '1px solid #bbf7d0', borderRadius: '10px', padding: '1.25rem', marginBottom: '1.5rem' }}>
                  <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '0.5rem', flexWrap: 'wrap', gap: '0.5rem' }}>
                    <div style={{ display: 'flex', alignItems: 'center', gap: '6px', color: '#166534', fontWeight: 800, fontSize: '1rem' }}>
                      <MapPin size={18} /> GPS Geolocation Extracted!
                    </div>
                    <div style={{ display: 'flex', gap: '0.5rem' }}>
                      <a
                        href={exifData.gps.osmUrl}
                        target="_blank"
                        rel="noopener noreferrer"
                        style={{ background: '#166534', color: '#ffffff', textDecoration: 'none', padding: '0.35rem 0.75rem', borderRadius: '6px', fontSize: '0.75rem', fontWeight: 700, display: 'inline-flex', alignItems: 'center', gap: '4px' }}
                      >
                        <span>OpenStreetMap</span> <ExternalLink size={12} />
                      </a>
                      <a
                        href={exifData.gps.mapsUrl}
                        target="_blank"
                        rel="noopener noreferrer"
                        style={{ background: '#ffffff', border: '1px solid #166534', color: '#166534', textDecoration: 'none', padding: '0.35rem 0.75rem', borderRadius: '6px', fontSize: '0.75rem', fontWeight: 700, display: 'inline-flex', alignItems: 'center', gap: '4px' }}
                      >
                        <span>Google Maps</span> <ExternalLink size={12} />
                      </a>
                    </div>
                  </div>

                  <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(200px, 1fr))', gap: '0.75rem', marginTop: '0.75rem' }}>
                    <div style={{ background: '#ffffff', padding: '0.65rem 0.85rem', borderRadius: '6px', border: '1px solid #dcfce7' }}>
                      <span style={{ fontSize: '0.72rem', color: '#15803d' }}>Decimal Coordinates</span>
                      <div style={{ fontWeight: 800, color: '#166534', fontFamily: 'monospace', fontSize: '0.85rem' }}>
                        {exifData.gps.latitude}, {exifData.gps.longitude}
                      </div>
                    </div>
                    <div style={{ background: '#ffffff', padding: '0.65rem 0.85rem', borderRadius: '6px', border: '1px solid #dcfce7' }}>
                      <span style={{ fontSize: '0.72rem', color: '#15803d' }}>Degrees / Minutes / Seconds</span>
                      <div style={{ fontWeight: 800, color: '#166534', fontFamily: 'monospace', fontSize: '0.85rem' }}>
                        {exifData.gps.latDMS}, {exifData.gps.lonDMS}
                      </div>
                    </div>
                    <div style={{ background: '#ffffff', padding: '0.65rem 0.85rem', borderRadius: '6px', border: '1px solid #dcfce7' }}>
                      <span style={{ fontSize: '0.72rem', color: '#15803d' }}>Recorded Altitude</span>
                      <div style={{ fontWeight: 800, color: '#166534', fontFamily: 'monospace', fontSize: '0.85rem' }}>
                        {exifData.gps.altitude}
                      </div>
                    </div>
                  </div>
                </div>
              ) : (
                <div style={{ background: '#f8fafc', border: '1px solid #e2e8f0', borderRadius: '8px', padding: '1rem', color: '#64748b', fontSize: '0.85rem', marginBottom: '1.5rem', display: 'flex', alignItems: 'center', gap: '8px' }}>
                  <Info size={16} /> No GPS coordinates found in this file (or location metadata has been scrubbed).
                </div>
              )}

              {/* Camera & Hardware Details */}
              <h4 style={{ fontSize: '0.95rem', fontWeight: 800, color: '#0f172a', marginBottom: '0.75rem' }}>
                Hardware & Software Signatures
              </h4>
              <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(220px, 1fr))', gap: '0.75rem', marginBottom: '1.5rem' }}>
                <div style={{ background: '#f8fafc', padding: '0.75rem', borderRadius: '6px', border: '1px solid #e2e8f0' }}>
                  <div style={{ fontSize: '0.72rem', color: '#64748b' }}>Camera Make</div>
                  <div style={{ fontSize: '0.85rem', fontWeight: 700, color: '#0f172a' }}>{exifData?.cameraMake || 'N/A'}</div>
                </div>
                <div style={{ background: '#f8fafc', padding: '0.75rem', borderRadius: '6px', border: '1px solid #e2e8f0' }}>
                  <div style={{ fontSize: '0.72rem', color: '#64748b' }}>Camera Model</div>
                  <div style={{ fontSize: '0.85rem', fontWeight: 700, color: '#0f172a' }}>{exifData?.cameraModel || 'N/A'}</div>
                </div>
                <div style={{ background: '#f8fafc', padding: '0.75rem', borderRadius: '6px', border: '1px solid #e2e8f0' }}>
                  <div style={{ fontSize: '0.72rem', color: '#64748b' }}>Editing Software (Tamper clue)</div>
                  <div style={{ fontSize: '0.85rem', fontWeight: 700, color: '#0f172a' }}>{exifData?.software || 'N/A'}</div>
                </div>
                <div style={{ background: '#f8fafc', padding: '0.75rem', borderRadius: '6px', border: '1px solid #e2e8f0' }}>
                  <div style={{ fontSize: '0.72rem', color: '#64748b' }}>Original Capture Date</div>
                  <div style={{ fontSize: '0.85rem', fontWeight: 700, color: '#0f172a' }}>{exifData?.dateTimeOriginal || exifData?.dateTime || 'N/A'}</div>
                </div>
              </div>

              {/* PDF Document Metadata (if PDF) */}
              {pdfData?.isPdf && (
                <>
                  <h4 style={{ fontSize: '0.95rem', fontWeight: 800, color: '#0f172a', marginBottom: '0.75rem' }}>
                    PDF Document Properties
                  </h4>
                  <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(220px, 1fr))', gap: '0.75rem' }}>
                    <div style={{ background: '#f8fafc', padding: '0.75rem', borderRadius: '6px', border: '1px solid #e2e8f0' }}>
                      <div style={{ fontSize: '0.72rem', color: '#64748b' }}>Author</div>
                      <div style={{ fontSize: '0.85rem', fontWeight: 700, color: '#0f172a' }}>{pdfData.metadata.author || 'Unspecified'}</div>
                    </div>
                    <div style={{ background: '#f8fafc', padding: '0.75rem', borderRadius: '6px', border: '1px solid #e2e8f0' }}>
                      <div style={{ fontSize: '0.72rem', color: '#64748b' }}>Producer / Generator Tool</div>
                      <div style={{ fontSize: '0.85rem', fontWeight: 700, color: '#0f172a' }}>{pdfData.metadata.producer || 'Unspecified'}</div>
                    </div>
                    <div style={{ background: '#f8fafc', padding: '0.75rem', borderRadius: '6px', border: '1px solid #e2e8f0' }}>
                      <div style={{ fontSize: '0.72rem', color: '#64748b' }}>Creation Date Tag</div>
                      <div style={{ fontSize: '0.85rem', fontWeight: 700, color: '#0f172a' }}>{pdfData.metadata.creationDate || 'Unspecified'}</div>
                    </div>
                  </div>
                </>
              )}
            </div>
          )}

          {/* TAB 4: STRINGS HUNTER */}
          {activeTab === 'strings' && (
            <div style={{ background: '#ffffff', border: '1px solid #e2e8f0', borderRadius: '14px', padding: '1.5rem', boxShadow: '0 4px 16px -2px rgba(0,0,0,0.03)' }}>
              <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '1rem', flexWrap: 'wrap', gap: '0.75rem' }}>
                <div>
                  <h3 style={{ fontSize: '1.15rem', fontWeight: 800, color: '#0f172a', margin: 0 }}>
                    Strings Hunter (Carved Printable Sequences)
                  </h3>
                  <p style={{ fontSize: '0.82rem', color: '#64748b', margin: '0.25rem 0 0 0' }}>
                    Scanning raw binary bytes for ASCII and UTF-8 strings. Analysts use this to find hardcoded C2 domains, commands, and secrets.
                  </p>
                </div>
                <span style={{ fontSize: '0.75rem', color: '#64748b', background: '#f1f5f9', padding: '0.2rem 0.6rem', borderRadius: '4px', fontWeight: 600 }}>
                  Found {stringsData.length} strings (showing {filteredStrings.length})
                </span>
              </div>

              {/* Filter pills & Search input */}
              <div style={{ display: 'flex', gap: '0.5rem', marginBottom: '1rem', flexWrap: 'wrap', alignItems: 'center', justifyContent: 'space-between' }}>
                <div style={{ display: 'flex', gap: '0.35rem', flexWrap: 'wrap' }}>
                  {['ALL', 'SUSPICIOUS', 'URL', 'IP', 'PATH', 'GENERAL'].map((cat) => (
                    <button
                      key={cat}
                      onClick={() => setStringCategoryFilter(cat)}
                      style={{
                        background: stringCategoryFilter === cat ? '#0f172a' : '#f1f5f9',
                        color: stringCategoryFilter === cat ? '#ffffff' : '#475569',
                        border: 'none',
                        padding: '0.35rem 0.75rem',
                        borderRadius: '6px',
                        fontSize: '0.75rem',
                        fontWeight: 700,
                        cursor: 'pointer'
                      }}
                    >
                      {cat}
                    </button>
                  ))}
                </div>
                <input
                  type="text"
                  placeholder="Filter strings..."
                  value={stringSearch}
                  onChange={(e) => setStringSearch(e.target.value)}
                  style={{
                    padding: '0.4rem 0.75rem',
                    border: '1px solid #cbd5e1',
                    borderRadius: '6px',
                    fontSize: '0.8rem',
                    minWidth: '220px'
                  }}
                />
              </div>

              {/* Strings List */}
              <div style={{
                maxHeight: '440px',
                overflowY: 'auto',
                background: '#090d16',
                borderRadius: '8px',
                padding: '0.75rem',
                fontFamily: 'monospace',
                fontSize: '0.8rem',
                border: '1px solid #1e293b'
              }}>
                {filteredStrings.length === 0 ? (
                  <div style={{ color: '#64748b', padding: '1rem', textAlign: 'center' }}>
                    No strings matching the filter criteria.
                  </div>
                ) : (
                  filteredStrings.map((item, idx) => (
                    <div
                      key={idx}
                      style={{
                        padding: '0.25rem 0.5rem',
                        borderBottom: '1px solid rgba(255,255,255,0.04)',
                        display: 'flex',
                        alignItems: 'center',
                        justifyContent: 'space-between',
                        gap: '1rem',
                        color: item.category === 'SUSPICIOUS' ? '#f87171' : item.category === 'URL' ? '#38bdf8' : item.category === 'IP' ? '#fbbf24' : '#e2e8f0'
                      }}
                    >
                      <span style={{ wordBreak: 'break-all' }}>{item.text}</span>
                      <div style={{ display: 'flex', alignItems: 'center', gap: '0.5rem', flexShrink: 0 }}>
                        <span style={{
                          fontSize: '0.65rem',
                          fontWeight: 700,
                          padding: '1px 5px',
                          borderRadius: '4px',
                          background: item.category === 'SUSPICIOUS' ? '#991b1b' : 'rgba(255,255,255,0.1)',
                          color: '#ffffff'
                        }}>
                          {item.category}
                        </span>
                        <button
                          onClick={() => copyToClipboard(item.text, `str-${idx}`)}
                          style={{ background: 'transparent', border: 'none', color: '#94a3b8', cursor: 'pointer', padding: 0 }}
                        >
                          {copiedKey === `str-${idx}` ? <Check size={12} color="#4ade80" /> : <Copy size={12} />}
                        </button>
                      </div>
                    </div>
                  ))
                )}
              </div>
            </div>
          )}

          {/* TAB 5: HEX INSPECTOR */}
          {activeTab === 'hex' && (
            <div style={{ background: '#ffffff', border: '1px solid #e2e8f0', borderRadius: '14px', padding: '1.5rem', boxShadow: '0 4px 16px -2px rgba(0,0,0,0.03)' }}>
              <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '1rem', flexWrap: 'wrap', gap: '0.75rem' }}>
                <div>
                  <h3 style={{ fontSize: '1.15rem', fontWeight: 800, color: '#0f172a', margin: 0 }}>
                    16-Byte Aligned Hex Inspector
                  </h3>
                  <p style={{ fontSize: '0.82rem', color: '#64748b', margin: '0.25rem 0 0 0' }}>
                    View raw byte values alongside ASCII interpretations. Switch between Header and Trailer to identify appended payloads past EOF.
                  </p>
                </div>

                <div style={{ display: 'flex', gap: '0.5rem' }}>
                  <button
                    onClick={() => updateHexView(null, 'header')}
                    style={{
                      background: hexViewMode === 'header' ? '#0f172a' : '#f1f5f9',
                      color: hexViewMode === 'header' ? '#ffffff' : '#334155',
                      border: 'none',
                      padding: '0.35rem 0.85rem',
                      borderRadius: '6px',
                      fontSize: '0.78rem',
                      fontWeight: 700,
                      cursor: 'pointer'
                    }}
                  >
                    Header (Offset 0x00)
                  </button>
                  <button
                    onClick={() => updateHexView(null, 'trailer')}
                    style={{
                      background: hexViewMode === 'trailer' ? '#0f172a' : '#f1f5f9',
                      color: hexViewMode === 'trailer' ? '#ffffff' : '#334155',
                      border: 'none',
                      padding: '0.35rem 0.85rem',
                      borderRadius: '6px',
                      fontSize: '0.78rem',
                      fontWeight: 700,
                      cursor: 'pointer'
                    }}
                  >
                    Trailer (End of File)
                  </button>
                </div>
              </div>

              <div style={{
                background: '#090d16',
                borderRadius: '8px',
                padding: '1rem',
                fontFamily: 'monospace',
                fontSize: '0.82rem',
                color: '#e2e8f0',
                overflowX: 'auto',
                border: '1px solid #1e293b'
              }}>
                <div style={{ display: 'grid', gridTemplateColumns: '90px 1fr 180px', color: '#64748b', fontWeight: 700, borderBottom: '1px solid #1e293b', paddingBottom: '0.35rem', marginBottom: '0.5rem' }}>
                  <span>OFFSET</span>
                  <span>HEX BYTES (00 - 0F)</span>
                  <span>ASCII</span>
                </div>
                {hexRows.map((row, idx) => (
                  <div key={idx} style={{ display: 'grid', gridTemplateColumns: '90px 1fr 180px', padding: '0.15rem 0' }}>
                    <span style={{ color: '#38bdf8' }}>{row.offset}</span>
                    <span style={{ color: '#f8fafc', letterSpacing: '0.5px' }}>{row.hex}</span>
                    <span style={{ color: '#4ade80' }}>{row.ascii}</span>
                  </div>
                ))}
              </div>
            </div>
          )}

          {/* TAB 6: CYBERSECURITY STUDENT FIELD GUIDE */}
          {activeTab === 'guide' && (
            <div style={{ background: '#ffffff', border: '1px solid #e2e8f0', borderRadius: '14px', padding: '1.75rem', boxShadow: '0 4px 16px -2px rgba(0,0,0,0.03)' }}>
              <div style={{ display: 'flex', alignItems: 'center', gap: '8px', marginBottom: '1rem' }}>
                <BookOpen size={20} color="#0f172a" />
                <h3 style={{ fontSize: '1.25rem', fontWeight: 800, color: '#0f172a', margin: 0 }}>
                  Cybersecurity Student Forensics Field Guide
                </h3>
              </div>
              <p style={{ fontSize: '0.88rem', color: '#64748b', lineHeight: 1.5, marginBottom: '1.5rem' }}>
                Essential principles every digital forensic investigator, SOC analyst, and CTF player should master.
              </p>

              <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(300px, 1fr))', gap: '1rem' }}>
                {/* Guide 1 */}
                <div style={{ background: '#f8fafc', border: '1px solid #e2e8f0', borderRadius: '10px', padding: '1.15rem' }}>
                  <h4 style={{ margin: '0 0 0.4rem 0', fontSize: '0.95rem', fontWeight: 800, color: '#0f172a' }}>
                    1. Chain of Custody & Hash Collisions
                  </h4>
                  <p style={{ margin: 0, fontSize: '0.82rem', color: '#475569', lineHeight: 1.45 }}>
                    Before touching digital evidence, compute a SHA-256 hash. In court, you must prove the evidence analyzed is identical to what was seized. While MD5 and SHA-1 are computationally broken for cryptographic security (collision attacks exist), they are still used in threat intelligence (VirusTotal) for rapid lookup.
                  </p>
                </div>

                {/* Guide 2 */}
                <div style={{ background: '#f8fafc', border: '1px solid #e2e8f0', borderRadius: '10px', padding: '1.15rem' }}>
                  <h4 style={{ margin: '0 0 0.4rem 0', fontSize: '0.95rem', fontWeight: 800, color: '#0f172a' }}>
                    2. Magic Bytes & File Masquerading
                  </h4>
                  <p style={{ margin: 0, fontSize: '0.82rem', color: '#475569', lineHeight: 1.45 }}>
                    An adversary can rename <code>malware.exe</code> to <code>photo.jpg</code> or <code>invoice.pdf</code>. Windows hides file extensions by default. Digital forensics tools ignore extensions and inspect the initial magic bytes (e.g. <code>4D 5A</code> for PE executables, <code>25 50 44 46</code> for PDF).
                  </p>
                </div>

                {/* Guide 3 */}
                <div style={{ background: '#f8fafc', border: '1px solid #e2e8f0', borderRadius: '10px', padding: '1.15rem' }}>
                  <h4 style={{ margin: '0 0 0.4rem 0', fontSize: '0.95rem', fontWeight: 800, color: '#0f172a' }}>
                    3. Shannon Entropy & Packing Detection
                  </h4>
                  <p style={{ margin: 0, fontSize: '0.82rem', color: '#475569', lineHeight: 1.45 }}>
                    Shannon entropy measures information density (0 to 8 bits). Plain text has low entropy (~3.5). Encrypted or packed payloads have high entropy (~7.5+). Malware authors pack code (using UPX or custom crypters) to evade signature scanners. High entropy flags packed sections immediately!
                  </p>
                </div>

                {/* Guide 4 */}
                <div style={{ background: '#f8fafc', border: '1px solid #e2e8f0', borderRadius: '10px', padding: '1.15rem' }}>
                  <h4 style={{ margin: '0 0 0.4rem 0', fontSize: '0.95rem', fontWeight: 800, color: '#0f172a' }}>
                    4. OSINT from EXIF & Geolocation
                  </h4>
                  <p style={{ margin: 0, fontSize: '0.82rem', color: '#475569', lineHeight: 1.45 }}>
                    Smartphones and cameras record GPS coordinates, camera serial numbers, and software edit history directly into photo headers. In Open Source Intelligence (OSINT), analysts use these coordinates to track physical locations of targets or suspects.
                  </p>
                </div>

                {/* Guide 5 */}
                <div style={{ background: '#f8fafc', border: '1px solid #e2e8f0', borderRadius: '10px', padding: '1.15rem' }}>
                  <h4 style={{ margin: '0 0 0.4rem 0', fontSize: '0.95rem', fontWeight: 800, color: '#0f172a' }}>
                    5. Steganography & Appended EOF Payloads
                  </h4>
                  <p style={{ margin: 0, fontSize: '0.82rem', color: '#475569', lineHeight: 1.45 }}>
                    Standard file formats have defined End-of-File markers (e.g. JPEG ends with <code>FF D9</code>). Attackers append hidden files or archives after the EOF marker. Viewers stop rendering at the EOF marker, but the appended bytes remain accessible to forensics tools.
                  </p>
                </div>

                {/* Guide 6 */}
                <div style={{ background: '#f8fafc', border: '1px solid #e2e8f0', borderRadius: '10px', padding: '1.15rem' }}>
                  <h4 style={{ margin: '0 0 0.4rem 0', fontSize: '0.95rem', fontWeight: 800, color: '#0f172a' }}>
                    6. Strings Carving & Static Analysis
                  </h4>
                  <p style={{ margin: 0, fontSize: '0.82rem', color: '#475569', lineHeight: 1.45 }}>
                    Strings carving is the first static analysis step when inspecting an unknown artifact. It quickly reveals Command-and-Control (C2) domains, registry persistence paths, hardcoded IP addresses, and user-agent strings without needing to execute the binary.
                  </p>
                </div>
              </div>
            </div>
          )}
        </>
      )}
    </div>
  );
}
